// music.js — ปุ่มเพลงพื้นหลังมุมล่างซ้าย (เล่น/หยุด + ปรับเสียง) และตัวอัปโหลดเพลงในหลังบ้าน
// ค่าเปิด/ระดับเสียงของผู้ใช้เก็บเฉพาะเครื่องนั้น (localStorage 'dx_mu')  ไฟล์เพลงเก็บใน S.cfg.music (ไม่เกิน 3.5 MB) หรือใช้ลิงก์ S.cfg.musicUrl
const MU={a:null,src:'',open:0,get(){try{return JSON.parse(localStorage.getItem('dx_mu'))||{}}catch(e){return{}}},set(o){try{localStorage.setItem('dx_mu',JSON.stringify({...MU.get(),...o}))}catch(e){}}};
const muSrc=()=>S.cfg.music||(S.cfg.musicUrl||'').trim(),muVol=()=>{const v=MU.get().vol;return v==null?40:v};
const SVG={play:'<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>',pause:'<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M7 5h4v14H7zM13 5h4v14h-4z"/></svg>',vol:'<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor"><path d="M3 9v6h4l5 4V5L7 9z"/><path d="M15.5 8.5a5 5 0 010 7M18 6a8.5 8.5 0 010 12" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',mute:'<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor"><path d="M3 9v6h4l5 4V5L7 9z"/><path d="M16 9l5 6m0-6l-5 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'};
function muAudio(){const s=muSrc();if(!MU.a){MU.a=new Audio();MU.a.loop=true;MU.a.addEventListener('play',muUI);MU.a.addEventListener('pause',muUI);MU.a.addEventListener('error',()=>{if(MU.a.src)toast('เล่นเพลงไม่ได้ ตรวจสอบไฟล์หรือลิงก์เพลงในหลังบ้าน')})}
if(s!==MU.src){MU.src=s;MU.a.pause();if(s)MU.a.src=s;else MU.a.removeAttribute('src')}MU.a.volume=muVol()/100;return MU.a}
function muToggle(){const a=muAudio();if(!muSrc())return;if(a.paused){MU.set({on:1});a.play().catch(()=>toast('เบราว์เซอร์ไม่อนุญาตให้เล่นเสียง ลองกดอีกครั้ง'))}else{MU.set({on:0});a.pause()}}
function muVolTog(){MU.open=!MU.open;muUI()}
function muSetVol(v){v=Math.max(0,Math.min(100,+v||0));MU.set({vol:v});if(MU.a)MU.a.volume=v/100;const b=document.querySelector('#mu .mv-b');if(b)b.innerHTML=v?SVG.vol:SVG.mute}
function muUI(){let w=$('mu');if(!muSrc()){if(w)w.remove();if(MU.a){MU.a.pause()}return}
const a=muAudio(),pl=!a.paused,v=muVol();if(!w){w=document.createElement('div');w.id='mu';document.body.append(w)}
w.innerHTML=`<button class="mc ${pl?'on':''}" onclick="muToggle()" title="${pl?'หยุดเพลง':'เล่นเพลง'}" aria-label="เพลง">${pl?SVG.pause:SVG.play}</button><button class="mc mv-b" onclick="muVolTog()" title="ปรับเสียง" aria-label="ปรับเสียง">${v?SVG.vol:SVG.mute}</button><div class="mvs ${MU.open?'':'hid'}"><input type="range" min="0" max="100" value="${v}" oninput="muSetVol(this.value)" aria-label="ระดับเสียง"></div>`}
document.addEventListener('pointerdown',function f(){document.removeEventListener('pointerdown',f);if(S.cfg.musicAuto&&muSrc()&&MU.get().on!==0){const a=muAudio();if(a.paused)a.play().catch(()=>{})}},{once:true});
function musicUp(f){if(!f)return;if(!/^audio\//.test(f.type)&&!/\.(mp3|wav|ogg|m4a|aac)$/i.test(f.name))return toast('กรุณาเลือกไฟล์เสียง (mp3, wav, ogg, m4a)');if(f.size>3.5*1048576)return toast('ไฟล์ใหญ่เกิน 3.5 MB ลดขนาดไฟล์ หรือใช้ลิงก์ไฟล์เพลงแทน');const r=new FileReader();r.onload=()=>{S.cfg.music=r.result;S.cfg.musicName=f.name;save();toast('อัปโหลดเพลงแล้ว');render()};r.readAsDataURL(f)}
function musicAdmin(){const c=S.cfg;return `<b>เพลงพื้นหลัง</b><div class="m" style="font-size:12px">ผู้เข้าชมจะเห็นปุ่มวงกลมเล่น/หยุดเพลงและปรับเสียงที่มุมล่างซ้าย (เบราว์เซอร์ไม่ให้เล่นเสียงเองจนกว่าผู้ใช้จะแตะหน้าเว็บ)</div><div><label>อัปโหลดไฟล์เพลง (mp3, wav, ogg, m4a ไม่เกิน 3.5 MB)</label><input type="file" accept="audio/*" onchange="musicUp(this.files[0]);this.value=''">${c.music?`<div class="r" style="margin-top:6px"><span class="tg">${E(c.musicName||'ไฟล์เพลง')}</span><a class="m" style="cursor:pointer" onclick="S.cfg.music='';S.cfg.musicName='';save();render()">ลบเพลง</a></div>`:''}</div><div><label>หรือใส่ลิงก์ไฟล์เพลง (ใช้เมื่อไม่ได้อัปโหลดไฟล์)</label><input placeholder="https://.../song.mp3" value="${E(c.musicUrl||'')}" onchange="S.cfg.musicUrl=this.value.trim();save();render()"></div><label class="tgl" style="margin:0;cursor:pointer;color:var(--t)"><span>เริ่มเล่นอัตโนมัติเมื่อผู้ใช้แตะหน้าเว็บครั้งแรก</span><input type="checkbox" ${c.musicAuto?'checked':''} onchange="S.cfg.musicAuto=this.checked?1:0;save()"></label>`}
