// shop.js — หน้าแรก, แบนเนอร์, สินค้า, ซื้อสินค้า, เติมเงิน (ฝั่งลูกค้า)
let bi=0;const bs=()=>{document.querySelectorAll('#bnr img').forEach((m,i)=>m.style.opacity=i==bi?1:0);document.querySelectorAll('#bnr i').forEach((m,i)=>m.className=i==bi?'on':'')};setInterval(()=>{const n=S.cfg.banners.length;if(n>1&&$('bnr')){bi=(bi+1)%n;bs()}},4000);
function home(){const c=S.cfg;if(bi>=c.banners.length)bi=0;return `${c.banners.length?`<div class="bnr" id="bnr">${c.banners.map((b,i)=>`<img src="${b}" style="opacity:${i==bi?1:0}">`).join('')}${c.banners.length>1?`<div class="dots">${c.banners.map((b,i)=>`<i class="${i==bi?'on':''}" onclick="bi=${i};bs()"></i>`).join('')}</div>`:''}</div>`:''}<div class="hero"><h2>${E(c.name)}</h2><p class="m" style="margin:8px 0 16px">${E(c.slogan)}</p><div class="r"><button class="btn" onclick="go('products')">เลือกซื้อสินค้า</button>${c.topup?`<button class="btn g" onclick="go('refill')">เติมเงิน</button>`:''}</div></div><div><h3 style="margin-bottom:10px">สินค้าแนะนำ</h3><div class="grid">${S.prods.slice(0,6).map(pcard).join('')}</div></div>`}
function pcard(p){const n=stk(p),c=S.cats.find(x=>x.id==p.cat),w=n?Math.max(12,Math.min(100,n*5)):0;return `<div class="pc"><div class="pi" onclick="openP(${p.id})" style="cursor:pointer">${p.img?`<img src="${p.img}" loading="lazy" alt="">`:'<i class="fa-solid fa-gamepad"></i>'}${p.tag?`<span class="ptag">${E(p.tag)}</span>`:''}</div><div class="bd"><span class="pcat">${E(c?c.name:'')}</span><b class="pn" style="cursor:pointer" onclick="openP(${p.id})" title="${E(p.name)}">${E(p.name)}</b><div class="prow"><span><small>เริ่ม</small> <b>${minP(p)} ฿</b></span><span class="pst">${n?`<span class="bar"><u style="width:${w}%"></u></span><small>มี ${n}</small>`:'<small>หมด</small>'}</span></div><button class="btn pbuy" ${n?'':'disabled'} onclick="openP(${p.id})">${n?'ซื้อทันที':'สินค้าหมด'}</button></div></div>`}
const pgH=()=>{const l=S.prods.filter(p=>(!cat||p.cat==cat)&&p.name.toLowerCase().includes(q));return l.map(pcard).join('')||'<span class="m">ไม่พบสินค้า</span>'};
function prodPage(){return `<div class="shop"><div class="cats"><button class="cc ${!cat?'on':''}" onclick="cat=0;render()"><i class="fa-solid fa-border-all"></i>ทั้งหมด</button>${S.cats.map(c=>`<button class="cc ${cat==c.id?'on':''}" onclick="cat=${c.id};render()">${c.img?`<img src="${c.img}">`:'<i class="fa-solid fa-tag"></i>'}${E(c.name)}</button>`).join('')}</div><div style="flex:1;display:grid;gap:12px"><input placeholder="ค้นหาสินค้า..." value="${E(q)}" oninput="q=this.value.toLowerCase();$('pg').innerHTML=pgH()"><div class="grid" id="pg">${pgH()}</div></div></div>`}
let DT={pid:0,vi:0,code:'',cp:null};
const rdisc=u=>u&&u!==S.adm?((S.ranks.find(r=>r.id==u.rank)||{}).disc||0):0,cpOk=c=>c&&(!c.max||(c.used||0)<c.max);
function calc(o){const base=o.price,rd=rb(base*rdisc(me)/100),a=rb(base-rd),c=DT.cp,cd=c?rb(c.type=='pct'?a*c.val/100:Math.min(c.val,a)):0;return{base,rd,cd,total:Math.max(0,rb(a-cd))}}
function openP(id){const p=S.prods.find(x=>x.id==id);if(!p)return;p.views=(p.views||0)+1;save();const vi=vars(p).findIndex(o=>o.items.length>0);DT={pid:id,vi:vi<0?0:vi,code:'',cp:null};page='product';render();scrollTo(0,0)}
function prodDetail(){const p=S.prods.find(x=>x.id==DT.pid);if(!p){page='products';return prodPage()}const v=vars(p),o=v[DT.vi]||v[0],c=S.cats.find(x=>x.id==p.cat),n=stk(p),k=calc(o),can=o.items.length>0,bd=(p.badges||'').split(',').map(x=>x.trim()).filter(Boolean);
return `<div class="pd"><div class="r"><button class="btn g s" onclick="go('products')" title="กลับ" style="font-size:20px;line-height:1;padding:3px 12px">‹</button><span class="m"><a style="cursor:pointer" onclick="go('products')">สินค้าทั้งหมด</a> / ${E(c?c.name:'')}</span></div>
<div class="pdg"><div style="display:grid;gap:12px;align-content:start"><div><span class="pcat">${E(c?c.name:'')}</span><h2 class="pdt">${E(p.name)}</h2></div><div class="r">${bd.map(x=>`<span class="tg n">${E(x)}</span>`).join('')}<span class="tg">ส่งอัตโนมัติ</span><span class="m" style="font-size:12px">ดูแล้ว ${p.views||0} ครั้ง</span></div>
<div class="pdi">${p.img?`<img src="${p.img}" alt="">`:'<i class="fa-solid fa-gamepad"></i>'}<span class="stb"><i></i> ${n?'เหลือ '+n+' ชิ้น':'สินค้าหมด'}</span></div>${p.desc?`<div class="card" style="white-space:pre-wrap">${E(p.desc)}</div>`:''}</div>
<div class="card pdp"><div><span class="pcat">เริ่มต้น</span><div class="r" style="align-items:baseline"><b class="pdpr">${minP(p)} ฿</b><span class="m">${v.length} ตัวเลือก</span></div><div class="m" style="font-size:12px;margin-top:6px">${me?`เครดิตคงเหลือ <b style="color:var(--t)">${money(me.bal)}</b> · ระดับ <span class="a">${E(rk(me))}</span>`:'เข้าสู่ระบบเพื่อดูเครดิตและสั่งซื้อ'}</div></div>
<div><label>เลือกตัวเลือก</label><div class="opts">${v.map((x,i)=>{const sn=x.items.length;return `<div class="opt ${i==DT.vi?'on':''} ${sn?'':'off'}" ${sn?`onclick="pickO(${i})"`:''}><span class="rdo"></span><b>${E(x.name||'มาตรฐาน')}</b>${sn?`<span class="tg">สต็อกร้าน (${sn})</span>`:'<span class="tg n">หมด</span>'}<span class="pp">${money(x.price)}</span></div>`}).join('')}</div></div>
<div class="r" style="flex-wrap:nowrap"><input id="cpi" placeholder="โค้ดส่วนลด" value="${E(DT.code)}" style="flex:1" onkeydown="if(event.key=='Enter')useCp()"><button class="btn g" onclick="useCp()">ใช้โค้ด</button></div>
<div class="sum"><div class="r sp"><span>${E(o.name||'มาตรฐาน')}</span><span>${money(k.base)}</span></div>${k.rd>0?`<div class="r sp a"><span>ส่วนลดยศ ${E(rk(me))} <span class="tg">${rdisc(me)}%</span></span><span>-${money(k.rd)}</span></div>`:''}${k.cd>0?`<div class="r sp a"><span>โค้ด ${E(DT.cp.code)}</span><span>-${money(k.cd)}</span></div>`:''}<div class="r sp tot"><b>ยอดชำระ</b><b>${money(k.total)}</b></div></div>
<button class="btn pbuy pdb" ${can?'':'disabled'} onclick="order()">${!can?'ตัวเลือกนี้หมด':!me?'เข้าสู่ระบบเพื่อสั่งซื้อ':me.bal<k.total?'ยอดเงินไม่พอ':'ยืนยันสั่งซื้อ · '+money(k.total)}</button>${me&&can&&me.bal<k.total&&S.cfg.topup?`<button class="btn g" onclick="go('refill')">เติมเงิน</button>`:''}</div></div></div>`}
function pickO(i){DT.vi=i;DT.code=$('cpi')?DT.code:'';render()}
function useCp(){const v=$('cpi').value.trim().toUpperCase();if(!v){DT.code='';DT.cp=null;return render()}const c=(S.coupons||[]).find(x=>x.code==v);if(!c||!cpOk(c))return toast('โค้ดไม่ถูกต้องหรือถูกใช้ครบแล้ว');DT.code=v;DT.cp=c;toast('ใช้โค้ดส่วนลดแล้ว');render()}
function order(){const p=S.prods.find(x=>x.id==DT.pid);if(!p)return;if(!me){toast('กรุณาเข้าสู่ระบบก่อน');return auth('l')}const o=vars(p)[DT.vi];if(!o||!o.items.length)return toast('ตัวเลือกนี้หมด');if(DT.cp&&!cpOk(DT.cp)){DT.cp=null;DT.code='';render();return toast('โค้ดส่วนลดถูกใช้ครบแล้ว')}const k=calc(o);if(me.bal<k.total){toast('ยอดเงินไม่พอ');return S.cfg.topup?go('refill'):0}
me.bal=rb(me.bal-k.total);const key=o.items.shift();if(DT.cp)DT.cp.used=(DT.cp.used||0)+1;const nm=p.name+(o.name?' · '+o.name:'');S.tx.unshift({id:uid(),date:now(),user:me.name,type:'buy',title:nm,amt:-k.total,key,st:'ok'});save();DT.cp=null;DT.code='';M(`<b>สั่งซื้อสำเร็จ</b><span>${E(nm)}</span><div class="st a" style="word-break:break-all;font-family:monospace">${E(key)}</div><div class="m" style="font-size:12px">เก็บรหัสนี้ไว้ ดูย้อนหลังได้ที่โปรไฟล์/ประวัติ</div><button class="btn" onclick="CM()">ตกลง</button>`);render()}
function refill(){const c=S.cfg,ms=[['qr','PromptPay','fa-qrcode',c.pqOn],['tw','TrueMoney ซอง','fa-envelope-open-text',c.ptOn],['code','โค้ดเติมเงิน','fa-ticket',c.pcOn]].filter(m=>m[3]);if(!ms.length)return `<div class="card m">ขณะนี้ยังไม่เปิดช่องทางเติมเงิน</div>`;if(!ms.some(m=>m[0]==pm))pm=ms[0][0];return `<div class="card" style="max-width:520px;margin:auto;display:grid;gap:12px"><h3><i class="fa-solid fa-wallet a"></i> เติมเงิน</h3><div class="r">${ms.map(m=>`<button class="btn ${pm==m[0]?'on':'g'}" onclick="pm='${m[0]}';render()"><i class="fa-solid ${m[2]}"></i> ${m[1]}</button>`).join('')}</div>${pm=='code'?`<div><label>กรอกโค้ด</label><input id="rc" placeholder="XXXX-XXXX"></div>`:`<div class="st m">${pm=='qr'?(c.qrimg?`<img src="${c.qrimg}" style="width:180px;display:block;margin:0 auto 8px;border-radius:10px">`:'')+E(c.pay)+'<br>โอนแล้วแนบสลิป แอดมินจะอนุมัติให้':(c.twPhone?'เบอร์รับซอง TrueMoney: <b class="a">'+c.twPhone.replace(/(\d{3})(\d{3})(\d{4})/,'$1-$2-$3')+'</b>':'ยังไม่ได้ตั้งเบอร์รับซอง')+'<br>'+(c.auto&&c.apiUrl?'ใส่ลิงก์ซองอั่งเปา ระบบตรวจและเติมเงินให้อัตโนมัติ':'ส่งลิงก์ซองอั่งเปา แอดมินจะตรวจสอบและอนุมัติ')}</div><div><label>จำนวนเงิน (บาท, ขั้นต่ำ ${c.min})</label><input id="ra" type="number" min="${c.min}"></div>${pm=='qr'?`<div><label>แนบสลิป</label><input type="file" accept="image/*" onchange="imgIn(this.files[0],700,v=>T.slip=v)"></div>`:`<div><label>ลิงก์ซองอั่งเปา</label><input id="rl" placeholder="https://gift.truemoney.com/..."></div>`}`}<button class="btn" onclick="topup()">ยืนยัน</button></div>`}
function topup(){if(!me){toast('กรุณาเข้าสู่ระบบ');return auth('l')}if(pm=='code'){const v=$('rc').value.trim().toUpperCase(),k=S.codes.find(x=>x.code==v&&!x.used);if(!k)return toast('โค้ดไม่ถูกต้องหรือถูกใช้แล้ว');k.used=me.name;me.bal=rb(me.bal+k.amt);S.tx.unshift({id:uid(),date:now(),user:me.name,type:'top',title:'โค้ดเติมเงิน '+v,amt:k.amt,st:'ok'});save();toast('เติมเงินสำเร็จ +'+k.amt);return render()}
if(T.api)return toast('กำลังตรวจสอบรายการก่อนหน้า กรุณารอสักครู่');if(S.tx.filter(x=>x.user==me.name&&x.st=='wait').length>=5)return toast('มีคำขอรออนุมัติครบ 5 รายการแล้ว');const a=rb(parseFloat($('ra').value));if(!(a>=S.cfg.min))return toast('ขั้นต่ำ '+S.cfg.min+' บาท');if(pm=='qr'&&!T.slip)return toast('กรุณาแนบสลิป');let vc='';if(pm=='tw'){const m=$('rl').value.trim().match(/gift\.truemoney\.com\/campaign\/\?v=([0-9A-Za-z]{10,64})/);if(!m)return toast('ลิงก์ซองไม่ถูกต้อง ต้องเป็นลิงก์ gift.truemoney.com');vc=m[1];if(S.tx.some(x=>x.vc==vc))return toast('ซองนี้ถูกส่งเข้ามาแล้ว')}const t={id:uid(),date:now(),user:me.name,type:'top',title:pm=='qr'?'PromptPay':'TrueMoney '+$('rl').value.trim(),amt:a,slip:pm=='qr'?T.slip:'',vc,st:'wait'},c=S.cfg,body={ref:t.id,user:me.name,method:pm,amount:a,slip:t.slip,voucher:pm=='tw'?$('rl').value.trim():'',phone:c.twPhone};T.slip='';S.tx.unshift(t);save();
if(!(c.auto&&c.apiUrl)){toast('ส่งคำขอแล้ว รอแอดมินอนุมัติ');return render()}
T.api=1;toast('กำลังตรวจสอบการชำระเงินอัตโนมัติ...');const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),15000);fetch(c.apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ac.signal}).then(x=>{if(!x.ok)throw 0;return x.json()}).then(d=>{if(d.success&&d.amount>0){t.amt=rb(+d.amount);t.st='ok';t.slip='';me.bal=rb(me.bal+t.amt);toast('เติมเงินสำเร็จ +'+t.amt)}else if(d.reject){t.st='no';toast(d.message||'การชำระเงินไม่ถูกต้อง')}else toast('รอแอดมินตรวจสอบ')}).catch(()=>toast('เชื่อมต่อระบบตรวจสอบไม่ได้ รอแอดมินอนุมัติ')).finally(()=>{clearTimeout(tm);T.api=0;save();render()})}
