// sync.js — ซิงค์ข้อมูลหลังบ้านไปเครื่องอื่น ผ่านเซิร์ฟเวอร์ของคุณ (server/dexter_payment_server.js)
// URL และรหัสซิงค์เก็บเฉพาะในเครื่องนี้ (localStorage 'dx_sync') ไม่รวมอยู่ในไฟล์ที่ส่งออก
const SY={get(){try{return JSON.parse(localStorage.getItem('dx_sync'))||{}}catch(e){return{}}},set(o){try{localStorage.setItem('dx_sync',JSON.stringify({...SY.get(),...o}))}catch(e){}}};
let syT=null,syBusy=0;
const syBase=()=>(SY.get().url||'').trim().replace(/\/+$/,''),syStat=m=>{const e=$('sys');if(e)e.textContent=m};
async function syReq(m,body){const c=SY.get();if(!syBase()||!c.key)throw new Error('ยังไม่ได้ใส่ URL และรหัสซิงค์');const ac=new AbortController(),t=setTimeout(()=>ac.abort(),25000);try{const r=await fetch(syBase()+'/state',{method:m,headers:{Authorization:'Bearer '+c.key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:ac.signal});if(r.status==401)throw new Error('รหัสซิงค์ไม่ถูกต้อง');if(r.status==429)throw new Error('ลองผิดหลายครั้ง รอ 1 นาที');if(r.status==503)throw new Error('เซิร์ฟเวอร์ยังไม่ได้ตั้ง ADMIN_TOKEN');if(!r.ok)throw new Error('เซิร์ฟเวอร์ตอบ '+r.status);return await r.json()}catch(e){throw e.name=='AbortError'?new Error('เชื่อมต่อเซิร์ฟเวอร์ไม่ทัน'):e}finally{clearTimeout(t)}}
async function syPush(manual){if(syBusy||!isAdmin)return;syBusy=1;try{const r=await syReq('PUT',{data:S});SY.set({last:r.ts});syStat('บันทึกขึ้นเซิร์ฟเวอร์ล่าสุด '+new Date(r.ts).toLocaleString('th-TH'));if(manual)toast('บันทึกขึ้นเซิร์ฟเวอร์แล้ว')}catch(e){syStat('ซิงค์ไม่สำเร็จ: '+e.message);toast('ซิงค์ไม่สำเร็จ: '+e.message)}finally{syBusy=0}}
function syncSoon(){if(!SY.get().auto||!isAdmin||syBusy)return;clearTimeout(syT);syT=setTimeout(()=>syPush(0),1500)}
async function syPull(){if(syBusy||!isAdmin)return;let r;syBusy=1;try{r=await syReq('GET')}catch(e){syBusy=0;return toast('ดึงข้อมูลไม่สำเร็จ: '+e.message)}syBusy=0;if(!r.data)return toast('บนเซิร์ฟเวอร์ยังไม่มีข้อมูล ให้กด "บันทึกขึ้นเซิร์ฟเวอร์" จากเครื่องหลักก่อน');
ask('ข้อมูลหลังบ้านในเครื่องนี้ทั้งหมด (สินค้า สต็อก สมาชิก ตั้งค่า) จะถูกแทนที่ด้วยข้อมูลจากเซิร์ฟเวอร์ที่บันทึกเมื่อ '+new Date(r.ts).toLocaleString('th-TH')+' รวมถึงรหัสแอดมิน',()=>{syBusy=1;Object.keys(S).forEach(k=>delete S[k]);Object.assign(S,r.data);const d=structuredClone(D);Object.keys(d).forEach(k=>{if(S[k]===undefined)S[k]=d[k]});S.cfg={...D.cfg,...S.cfg};S.prods.forEach(p=>{if(!Array.isArray(p.items))p.items=[]});me=S.adm;save();SY.set({last:r.ts});syBusy=0;toast('ดึงข้อมูลจากเซิร์ฟเวอร์แล้ว');render()},'แทนที่ข้อมูลในเครื่องนี้?','ดึงข้อมูล')}
function syncUI(){const c=SY.get();return `<b>ซิงค์ข้อมูลหลังบ้านไปเครื่องอื่น</b><div class="m" style="font-size:12px">ต้องมีเซิร์ฟเวอร์ของคุณ (ไฟล์ server/dexter_payment_server.js ตั้ง ADMIN_TOKEN) เครื่องหลักกด "บันทึกขึ้นเซิร์ฟเวอร์" เครื่องอื่นเข้าหลังบ้านแล้วกด "ดึงข้อมูล" ข้อมูลจะตามมาครบ ลูกค้าทั่วไปไม่เห็นส่วนนี้</div><div class="g2"><div><label>URL เซิร์ฟเวอร์</label><input placeholder="https://โดเมนของคุณ" value="${E(c.url||'')}" onchange="SY.set({url:this.value.trim()})"></div><div><label>รหัสซิงค์ (ADMIN_TOKEN)</label><input type="password" autocomplete="off" value="${E(c.key||'')}" onchange="SY.set({key:this.value})"></div></div><label class="tgl" style="margin:0;cursor:pointer;color:var(--t)"><span>บันทึกขึ้นเซิร์ฟเวอร์อัตโนมัติทุกครั้งที่แก้ไข</span><input type="checkbox" ${c.auto?'checked':''} onchange="SY.set({auto:this.checked});if(this.checked)syPush(1)"></label><div class="r"><button class="btn" onclick="syPush(1)"><i class="fa-solid fa-cloud-arrow-up"></i> บันทึกขึ้นเซิร์ฟเวอร์</button><button class="btn g" onclick="syPull()"><i class="fa-solid fa-cloud-arrow-down"></i> ดึงข้อมูล</button></div><div class="m" id="sys" style="font-size:12px">${c.last?'บันทึกขึ้นเซิร์ฟเวอร์ล่าสุด '+new Date(c.last).toLocaleString('th-TH'):'ยังไม่เคยซิงค์'}</div>`}
